// Code generated by goctl. DO NOT EDIT.
// Source: authorization.proto

package server

import (
	"context"

	"github.com/xh-polaris/meowchat-authorization-rpc/internal/logic"
	"github.com/xh-polaris/meowchat-authorization-rpc/internal/svc"
	"github.com/xh-polaris/meowchat-authorization-rpc/pb"
)

type AuthorizationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthorizationServer
}

func NewAuthorizationServer(svcCtx *svc.ServiceContext) *AuthorizationServer {
	return &AuthorizationServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthorizationServer) Allow(ctx context.Context, in *pb.AllowReq) (*pb.AllowResp, error) {
	l := logic.NewAllowLogic(ctx, s.svcCtx)
	return l.Allow(in)
}
